[versions]
agp = "8.7.3"
junit = "4.13.2"
room = "2.6.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
